M48
; DRILL file {KiCad (6.0.0)} date Fri Mar 25 10:46:27 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-25T10:46:27+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.478Y-2.2539
X3.4878Y-5.2303
X7.7677Y-2.2736
X7.7843Y-5.2421
T0
M30
